# Generated by Django 5.2.17 on 2026-10-03 12:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0009_organization_paystack_subaccount_code"),
        ("pricing", "0002_remediate_legacy_pricing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique event ID / reference from Paystack.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Event type, e.g. charge.success.", max_length=100
                    ),
                ),
                (
                    "payload",
                    models.JSONField(help_text="Full payload received from Paystack."),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-processed_at"],
            },
        ),
        migrations.CreateModel(
            name="FamilyPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshotted amount in NGN at initialization. Never recomputed.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="NGN",
                        help_text="Tuition currency, matching payouts (NGN).",
                        max_length=3,
                    ),
                ),
                (
                    "paystack_reference",
                    models.CharField(
                        db_index=True,
                        help_text="Server-generated unique reference sent to Paystack.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="pending",
                        help_text="pending -> paid | failed | abandoned.",
                        max_length=20,
                    ),
                ),
                (
                    "raw_webhook_payload",
                    models.JSONField(
                        blank=True,
                        help_text="Raw payload from Paystack charge.success webhook.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when charge.success finalized this payment.",
                        null=True,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        help_text="User who initiated payment (adult student or parent; never a minor).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_tuition_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The academy receiving this tuition directly via Paystack subaccount.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="family_tuition_payments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "pricing_agreement",
                    models.ForeignKey(
                        help_text="The PricingAgreement snapshot this payment satisfies.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="pricing.pricingagreement",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Student whose tuition is being paid. Must have role 'student'.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="family_tuition_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
