# Generated by Django 5.2.17 on 2026-08-24 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherBookingLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Bumped once per acquisition. The number is only ever diagnostic — how many booking writes have contended for this teacher — but the write that changes it is the lock itself.",
                    ),
                ),
                (
                    "teacher",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_lock",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
