# Generated by Django 5.2.17 on 2026-08-24 18:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0001_initial"),
        ("scheduling", "0002_teacherbookinglock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="routed_reason",
            field=models.CharField(
                choices=[
                    ("lead_available", "Routed to the lead teacher, who had capacity"),
                    ("lead_full_routed", "Lead teacher full, routed to a sub teacher"),
                    (
                        "student_choice",
                        "Teacher named directly by the student or parent",
                    ),
                    ("cohort_assigned", "Assigned a seat in an open cohort"),
                ],
                default="student_choice",
                help_text="How this booking's teacher was decided. Defaults to 'student_choice', which is what Phase 3's direct booking is.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_students",
                    models.PositiveIntegerField(
                        default=6,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "schedule_start_utc",
                    models.DateTimeField(help_text="Stored UTC, always."),
                ),
                (
                    "level",
                    models.ForeignKey(
                        help_text="Must have group_eligible=True.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cohorts",
                        to="curriculum.level",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Capped at max_students. Use add_student(); a raw students.add() is caught by the m2m_changed receiver in signals.py rather than silently overfilling the class.",
                        related_name="cohort_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="Role 'lead' or 'sub', approved, and a specialist in the level's track.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cohorts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["schedule_start_utc", "pk"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="cohort",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this booking is a seat in a group class rather than a 1:1 session. Its teacher, level and start must match the cohort's.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="seat_bookings",
                to="scheduling.cohort",
            ),
        ),
    ]
