# Generated by Django 5.2.17 on 2026-08-25 10:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0001_initial"),
        ("scheduling", "0003_booking_routed_reason_cohort_booking_cohort"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherWaitlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_start_utc",
                    models.DateTimeField(
                        help_text="The slot the family asked for, stored UTC. Not in the spec's field list — added with explicit approval so a promotion knows what time to offer."
                    ),
                ),
                (
                    "requested_duration_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Length of the session asked for. Added alongside the start.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Set by hand, never computed. The product owner's call (2026-08-25) on this phase's open question was that a premium_direct pricing agreement does *not* buy queue position, so nothing in the code writes this field — a lead raises it deliberately or not at all.",
                    ),
                ),
                (
                    "notified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the family has been told a slot opened. Nothing in this phase sets it: automatic notification is explicitly out of scope (see tech-debt.md), so it is here for the phase that delivers it.",
                    ),
                ),
                (
                    "fulfilled_booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when this entry is promoted into a real session. The entry then stays as a record rather than being deleted.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fulfilled_waitlist_entries",
                        to="scheduling.booking",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waitlist_entries",
                        to="curriculum.level",
                    ),
                ),
                (
                    "requested_teacher",
                    models.ForeignKey(
                        help_text="The teacher this family asked for by name. Role 'lead' or 'sub'.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waitlist_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Role 'student'.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "requested_at", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("fulfilled_booking__isnull", True)),
                        fields=(
                            "student",
                            "requested_teacher",
                            "level",
                            "requested_start_utc",
                        ),
                        name="unique_open_waitlist_request",
                        violation_error_message="That student is already on this teacher's waitlist for that slot.",
                    )
                ],
            },
        ),
    ]
