# Generated by Django 5.2.17 on 2026-08-26 18:51
#
# Phase 6, and a no-op at the database level (`sqlmigrate` prints "(no-op)").
# `TeacherBookingLock.revision` used to be the lock itself — bumping it was the
# write that took SQLite's database lock, because SQLite has no row locks. On
# PostgreSQL acquisition is an explicit SELECT ... FOR UPDATE, so the revision is
# now purely diagnostic and its help_text says so. Nothing about the column
# changed; only what it means.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0004_teacherwaitlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherbookinglock",
            name="revision",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="Bumped once per acquisition. The number is only ever diagnostic — how many booking writes have contended for this teacher — and since Phase 6 it is no longer the lock itself: SELECT ... FOR UPDATE is.",
            ),
        ),
    ]



class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0004_teacherwaitlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherbookinglock",
            name="revision",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="Bumped once per acquisition. The number is only ever diagnostic — how many booking writes have contended for this teacher — and since Phase 6 it is no longer the lock itself: SELECT ... FOR UPDATE is.",
            ),
        ),
    ]
