# Generated by Django 5.2.17 on 2026-09-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0008_enforce_availability_tenancy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="video_room_name",
        ),
        migrations.AddField(
            model_name="booking",
            name="video_join_url",
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="booking",
            name="video_provider",
            field=models.CharField(default="jitsi", max_length=32),
        ),
        migrations.AddField(
            model_name="booking",
            name="video_provider_meeting_id",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
