# Generated by Django 5.2.17 on 2026-09-29 16:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_studentenrollment_teacher"),
        ("scheduling", "0009_remove_booking_video_room_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassSessionRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("video_room_name", models.CharField(blank=True, max_length=128)),
                ("recording_url", models.URLField(blank=True, max_length=1024)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Retention expiry date — automatically purged after 60 days."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("processing", "Processing"),
                            ("purged", "Purged"),
                        ],
                        default="ready",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "booking",
                    models.ForeignKey(
                        help_text="The completed class session this recording belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="scheduling.booking",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Academy ownership for tenant isolation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_recordings",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at", "-pk"],
            },
        ),
    ]
