# Generated by Django 5.2.17 on 2026-09-12 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logs", "0001_initial"),
        ("organizations", "0003_alter_organization_video_provider"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="actor_id_snapshot",
            field=models.CharField(
                blank=True,
                help_text="Preserves actor ID if the user is deleted",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="actor_type",
            field=models.CharField(
                choices=[("USER", "User"), ("SYSTEM", "System")],
                default="USER",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("auth.login_success", "Login Success"),
                    ("auth.login_failed", "Login Failed"),
                    ("auth.logout", "Logout"),
                    ("auth.password_changed", "Password Changed"),
                    ("auth.password_reset_requested", "Password Reset Requested"),
                    ("organization.created", "Organization Created"),
                    ("organization.settings_updated", "Organization Settings Updated"),
                    ("membership.created", "Membership Created"),
                    ("membership.role_changed", "Membership Role Changed"),
                    ("membership.suspended", "Membership Suspended"),
                    ("membership.reactivated", "Membership Reactivated"),
                    ("permission.changed", "Permission Changed"),
                    ("curriculum.track_created", "Track Created"),
                    ("curriculum.track_updated", "Track Updated"),
                    ("curriculum.track_archived", "Track Archived"),
                    ("curriculum.level_created", "Level Created"),
                    ("curriculum.level_updated", "Level Updated"),
                    ("curriculum.level_archived", "Level Archived"),
                    (
                        "curriculum.teacher_assignment_changed",
                        "Teacher Assignment Changed",
                    ),
                    ("enrollment.created", "Enrollment Created"),
                    ("enrollment.updated", "Enrollment Updated"),
                    ("enrollment.withdrawn", "Enrollment Withdrawn"),
                    ("availability.created", "Availability Created"),
                    ("availability.updated", "Availability Updated"),
                    ("availability.deleted", "Availability Deleted"),
                    ("booking.created", "Booking Created"),
                    ("booking.updated", "Booking Updated"),
                    ("booking.cancelled", "Booking Cancelled"),
                    ("booking.completed", "Booking Completed"),
                    ("booking.no_show", "Booking No Show"),
                    ("cohort.created", "Cohort Created"),
                    ("cohort.updated", "Cohort Updated"),
                    ("cohort.cancelled", "Cohort Cancelled"),
                    ("cohort.assignment_changed", "Cohort Assignment Changed"),
                    ("assessment.created", "Assessment Created"),
                    ("assessment.updated", "Assessment Updated"),
                    ("assessment.finalized", "Assessment Finalized"),
                    ("assessment.reopened", "Assessment Reopened"),
                    ("pricing.agreement_created", "Agreement Created"),
                    ("pricing.agreement_updated", "Agreement Updated"),
                    ("pricing.agreement_deactivated", "Agreement Deactivated"),
                    ("pricing.rate_changed", "Rate Changed"),
                    ("payout.created", "Payout Created"),
                    ("payout.finalized", "Payout Finalized"),
                    ("payout.reopened", "Payout Reopened"),
                    ("notification.provider_updated", "Notification Provider Updated"),
                    (
                        "notification.configuration_updated",
                        "Notification Configuration Updated",
                    ),
                    ("notification.sent", "Notification Sent"),
                    ("video.provider_updated", "Video Provider Updated"),
                    ("video.meeting_created", "Meeting Created"),
                    ("video.meeting_updated", "Meeting Updated"),
                    ("video.meeting_cancelled", "Meeting Cancelled"),
                    ("bulk_import.started", "Bulk Import Started"),
                    ("bulk_import.validated", "Bulk Import Validated"),
                    ("bulk_import.completed", "Bulk Import Completed"),
                    ("bulk_import.failed", "Bulk Import Failed"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_type",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_logs",
                to="organizations.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="audit_logs__organiz_adc99e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["organization", "action", "-created_at"],
                name="audit_logs__organiz_95fd6d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["organization", "actor", "-created_at"],
                name="audit_logs__organiz_8ac4bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["organization", "object_type", "object_id", "-created_at"],
                name="audit_logs__organiz_055b7e_idx",
            ),
        ),
    ]
