# Generated by Django 5.2.17 on 2026-09-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logs", "0003_protect_audit_logs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("auth.login_success", "Login Success"),
                    ("auth.login_failed", "Login Failed"),
                    ("auth.logout", "Logout"),
                    ("auth.password_changed", "Password Changed"),
                    ("auth.password_reset_requested", "Password Reset Requested"),
                    ("organization.created", "Organization Created"),
                    ("organization.settings_updated", "Organization Settings Updated"),
                    ("membership.created", "Membership Created"),
                    ("membership.role_changed", "Membership Role Changed"),
                    ("membership.suspended", "Membership Suspended"),
                    ("membership.reactivated", "Membership Reactivated"),
                    ("invitation.created", "Invitation Created"),
                    ("invitation.resent", "Invitation Resent"),
                    ("invitation.revoked", "Invitation Revoked"),
                    ("invitation.accepted", "Invitation Accepted"),
                    ("invitation.email_failed", "Invitation Email Failed"),
                    ("permission.changed", "Permission Changed"),
                    ("curriculum.track_created", "Track Created"),
                    ("curriculum.track_updated", "Track Updated"),
                    ("curriculum.track_archived", "Track Archived"),
                    ("curriculum.level_created", "Level Created"),
                    ("curriculum.level_updated", "Level Updated"),
                    ("curriculum.level_archived", "Level Archived"),
                    (
                        "curriculum.teacher_assignment_changed",
                        "Teacher Assignment Changed",
                    ),
                    ("enrollment.created", "Enrollment Created"),
                    ("enrollment.updated", "Enrollment Updated"),
                    ("enrollment.withdrawn", "Enrollment Withdrawn"),
                    ("availability.created", "Availability Created"),
                    ("availability.updated", "Availability Updated"),
                    ("availability.deleted", "Availability Deleted"),
                    ("booking.created", "Booking Created"),
                    ("booking.updated", "Booking Updated"),
                    ("booking.cancelled", "Booking Cancelled"),
                    ("booking.completed", "Booking Completed"),
                    ("booking.no_show", "Booking No Show"),
                    ("cohort.created", "Cohort Created"),
                    ("cohort.updated", "Cohort Updated"),
                    ("cohort.cancelled", "Cohort Cancelled"),
                    ("cohort.assignment_changed", "Cohort Assignment Changed"),
                    ("assessment.created", "Assessment Created"),
                    ("assessment.updated", "Assessment Updated"),
                    ("assessment.finalized", "Assessment Finalized"),
                    ("assessment.reopened", "Assessment Reopened"),
                    ("pricing.agreement_created", "Agreement Created"),
                    ("pricing.agreement_updated", "Agreement Updated"),
                    ("pricing.agreement_deactivated", "Agreement Deactivated"),
                    ("pricing.rate_changed", "Rate Changed"),
                    ("payout.created", "Payout Created"),
                    ("payout.finalized", "Payout Finalized"),
                    ("payout.reopened", "Payout Reopened"),
                    ("notification.provider_updated", "Notification Provider Updated"),
                    (
                        "notification.configuration_updated",
                        "Notification Configuration Updated",
                    ),
                    ("notification.sent", "Notification Sent"),
                    ("video.provider_updated", "Video Provider Updated"),
                    ("video.meeting_created", "Meeting Created"),
                    ("video.meeting_updated", "Meeting Updated"),
                    ("video.meeting_cancelled", "Meeting Cancelled"),
                    ("bulk_import.started", "Bulk Import Started"),
                    ("bulk_import.validated", "Bulk Import Validated"),
                    ("bulk_import.completed", "Bulk Import Completed"),
                    ("bulk_import.failed", "Bulk Import Failed"),
                ],
                max_length=128,
            ),
        ),
    ]
