# Generated by Django 5.2.17 on 2026-10-03 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0009_organization_paystack_subaccount_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique event ID from Paystack webhook.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Paystack event name (e.g. subscription.create, invoice.payment_failed).",
                        max_length=100,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(help_text="Raw payload received from Paystack."),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-processed_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paystack_plan_code",
                    models.CharField(
                        help_text="Paystack Plan code for IqraLMS platform access.",
                        max_length=100,
                    ),
                ),
                (
                    "paystack_customer_code",
                    models.CharField(
                        help_text="Paystack Customer code for the academy owner.",
                        max_length=100,
                    ),
                ),
                (
                    "paystack_subscription_code",
                    models.CharField(
                        blank=True,
                        help_text="Paystack Subscription code.",
                        max_length=100,
                    ),
                ),
                (
                    "paystack_email_token",
                    models.CharField(
                        blank=True,
                        help_text="Email token provided by Paystack to disable/manage subscription.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("not_renewing", "Not Renewing"),
                            ("disabled", "Disabled"),
                        ],
                        default="active",
                        help_text="Current subscription lifecycle status.",
                        max_length=30,
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="End of the current paid billing period.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        help_text="The academy holding this platform subscription.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_subscription",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
