# Generated by Django 5.2.17 on 2026-08-30 10:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        ("scheduling", "0005_alter_teacherbookinglock_revision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentRubric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="False once a later rubric for the same track supersedes this one. Superseded rubrics are kept: historical assessments reference their criteria.",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_rubrics",
                        to="curriculum.track",
                    ),
                ),
            ],
            options={
                "ordering": ["track", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentCriterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Position on the sheet, 1 first. Unique within the rubric.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="False stops *new* assessments scoring it. Existing scores are untouched — deactivating is not deleting.",
                    ),
                ),
                (
                    "rubric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="assessment.assessmentrubric",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "assessment criteria",
                "ordering": ["rubric", "order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ProgressSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(help_text="Inclusive. Stored UTC."),
                ),
                (
                    "period_end",
                    models.DateTimeField(help_text="Exclusive. Stored UTC."),
                ),
                (
                    "generated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "completed_sessions",
                    models.PositiveIntegerField(
                        help_text="Sessions taught in the period, assessed or not."
                    ),
                ),
                (
                    "assessed_sessions",
                    models.PositiveIntegerField(
                        help_text="How many of those carry an assessment. Never inflated to match."
                    ),
                ),
                (
                    "overall_average",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Null when nothing in the period was assessed. Deliberately nullable: 'no assessments' is missing data, and 0.00 would read as a score of zero out of five.",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "criterion_averages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Snapshot of the per-criterion averages: [{criterion_id, criterion_name, average, score_count}].",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Short human line. Auto-composed from the numbers unless the lead supplies one.",
                    ),
                ),
                (
                    "visible_to_family",
                    models.BooleanField(
                        default=False,
                        help_text="Off until the lead publishes it. A family reads only published snapshots.",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The lead who generated it. Nullable so removing an account cannot take history with it.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progress_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progress_snapshots",
                        to="curriculum.track",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="SessionAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When it was submitted. Stored UTC, rendered per-viewer.",
                    ),
                ),
                (
                    "teacher_summary",
                    models.TextField(
                        blank=True,
                        help_text="Written for the family: this is the one free-text field they read.",
                    ),
                ),
                (
                    "flagged_for_review",
                    models.BooleanField(
                        default=False,
                        help_text="The teacher asking the lead to look at this session.",
                    ),
                ),
                (
                    "flag_reason",
                    models.TextField(
                        blank=True,
                        help_text="Why it was flagged. Internal — never shown to a student or parent.",
                    ),
                ),
                (
                    "lead_reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set by an explicit lead action. Viewing an assessment does not set it.",
                        null=True,
                    ),
                ),
                (
                    "lead_review_note",
                    models.TextField(
                        blank=True,
                        help_text="The lead's private annotation. Not visible to the family, and not visible to the assessing sub-teacher either in this phase.",
                    ),
                ),
                (
                    "rubric_name",
                    models.CharField(
                        help_text="Snapshot of the rubric's name at submission time.",
                        max_length=80,
                    ),
                ),
                (
                    "criteria_snapshot",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Snapshot of the criteria scored: [{id, name, order}]. What the teacher was actually looking at, frozen.",
                    ),
                ),
                (
                    "assessed_by",
                    models.ForeignKey(
                        help_text="Always booking.teacher, and an approved teacher.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment",
                        to="scheduling.booking",
                    ),
                ),
                (
                    "lead_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The lead teacher who reviewed. Nobody else may.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Always booking.student. Denormalised so progress can filter cheaply.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        help_text="Always booking.level.track — the track whose rubric was used.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="session_assessments",
                        to="curriculum.track",
                    ),
                ),
            ],
            options={
                "ordering": ["-assessed_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criterion_name",
                    models.CharField(
                        help_text="Snapshot of the criterion's name at submission time.",
                        max_length=120,
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        help_text="1 needs significant improvement .. 5 excellent.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Optional per-criterion note. Teaching feedback, not internal QC.",
                    ),
                ),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scores",
                        to="assessment.assessmentcriterion",
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="assessment.sessionassessment",
                    ),
                ),
            ],
            options={
                "ordering": ["assessment", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="assessmentrubric",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("track",),
                name="unique_active_rubric_per_track",
                violation_error_message="That track already has an active assessment rubric.",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentcriterion",
            constraint=models.UniqueConstraint(
                fields=("rubric", "order"),
                name="unique_criterion_order_per_rubric",
                violation_error_message="That rubric already has a criterion at this position.",
            ),
        ),
        migrations.AddConstraint(
            model_name="progresssnapshot",
            constraint=models.UniqueConstraint(
                fields=("student", "track", "period_start", "period_end"),
                name="unique_snapshot_per_student_track_period",
                violation_error_message="A snapshot for that student, track and period already exists.",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentscore",
            constraint=models.UniqueConstraint(
                fields=("assessment", "criterion"),
                name="unique_score_per_criterion_per_assessment",
                violation_error_message="That criterion is already scored on this assessment.",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentscore",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", 1), ("score__lte", 5)),
                name="score_within_scale",
                violation_error_message="Scores run 1 to 5.",
            ),
        ),
    ]
