# Generated by Django 5.2.17 on 2026-09-29 19:08

import assessment.models
import curriculum.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0002_remediate_legacy_assessment"),
        ("curriculum", "0005_learningmaterial"),
        ("organizations", "0008_studentenrollment_teacher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("audio_recitation", "Quran Audio Recitation"),
                            ("written_text", "Written Response"),
                            ("file_upload", "File / Worksheet Upload"),
                            ("mixed", "Mixed (Audio, Text, or File)"),
                        ],
                        default="audio_recitation",
                        max_length=30,
                    ),
                ),
                (
                    "surah_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Optional Quran Surah number (1-114)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(114),
                        ],
                    ),
                ),
                (
                    "ayah_start",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional starting Ayah number",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "ayah_end",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional ending Ayah number",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("max_score", models.PositiveIntegerField(default=100)),
                (
                    "resource_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=assessment.models.assignment_resource_path,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_student",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: specific student this assignment is directed to. Null = whole class/track.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="individual_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="curriculum.level",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "rubric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="assessment.assessmentrubric",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignments",
                        to="curriculum.track",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_recording",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=assessment.models.assignment_audio_path,
                        validators=[curriculum.validators.validate_placement_audio],
                    ),
                ),
                ("written_response", models.TextField(blank=True)),
                (
                    "attachment_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=assessment.models.assignment_attachment_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                            ("resubmission_requested", "Resubmission Requested"),
                        ],
                        default="submitted",
                        max_length=30,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("teacher_feedback", models.TextField(blank=True)),
                (
                    "rubric_scores",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Snapshot of criteria scores: [{criterion_id, criterion_name, score, comment}]",
                    ),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_assignment_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignment_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="assessment.studentassignment",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at", "-pk"],
            },
        ),
    ]
