# Generated by Django 5.2.17 on 2026-08-25 10:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "standard_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What this level would normally cost, snapshotted when the agreement was made. Deliberately stored rather than derived, so changing the standard rate later cannot silently reprice an existing agreement.",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "agreed_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What was actually negotiated. May equal standard_rate.",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("discount_hardship", "Discount — financial hardship"),
                            (
                                "premium_direct",
                                "Premium — chose the lead teacher directly",
                            ),
                            ("sibling_discount", "Sibling discount"),
                            ("standard", "Standard — no negotiation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Private: what was actually agreed and why. Never exposed to the student or their parent — see serializers.py.",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="False once a later agreement for the same student and level supersedes this one. Superseded rows are kept, never deleted.",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        help_text="The lead teacher. Nobody else may approve a rate.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pricing_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        help_text="A student can hold a different arrangement per level.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pricing_agreements",
                        to="curriculum.level",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        help_text="Role 'student'. Pricing is per student, not per family.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("student", "level"),
                        name="unique_active_pricing_per_student_level",
                        violation_error_message="That student already has an active pricing agreement for this level.",
                    )
                ],
            },
        ),
    ]
