# Generated by Django 5.2.17 on 2026-09-05 12:27

import accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable institution name, e.g. 'Al-Huda Quran Academy'. Not unique — two academies may legitimately choose similar names.",
                        max_length=120,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Machine-readable identifier, e.g. 'al-huda-quran-academy'. Globally unique, because the organization is itself the tenant and so has nothing to be scoped within.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        help_text="IANA zone name, e.g. 'Africa/Lagos'. The academy's own zone, validated by the same rule as User.timezone.",
                        max_length=64,
                        validators=[accounts.validators.validate_iana_timezone],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the academy is operating. Disabling an organization is a later phase's workflow, so nothing reads this yet — access is decided by active membership alone (see learnings.md).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Administrator"),
                            ("staff", "Staff"),
                            ("teacher", "Teacher"),
                        ],
                        help_text="Authority inside this academy. Independent of User.role — a user may be 'teacher' here and 'student' globally.",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended")],
                        default="active",
                        help_text="active grants tenant access; suspended keeps the row and revokes it.",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["organization_id", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "user"),
                        name="unique_organization_membership",
                        violation_error_message="That user is already a member of this organization. Change the existing membership instead of adding a second one.",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("role", "owner")),
                        fields=("organization",),
                        name="unique_owner_per_organization",
                        violation_error_message="This organization already has an owner. Transferring ownership is a separate operation, not a role change.",
                    ),
                ],
            },
        ),
    ]
