# Generated by Django 5.2.17 on 2026-09-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="video_provider",
            field=models.CharField(
                default="jitsi",
                help_text="The preferred video provider for this academy.",
                max_length=32,
            ),
        ),
    ]
