# Generated by Django 5.2.17 on 2026-09-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_video_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="video_provider",
            field=models.CharField(
                choices=[("jitsi", "Jitsi")],
                default="jitsi",
                help_text="The preferred video provider for this academy.",
                max_length=32,
            ),
        ),
    ]
