# Generated by Django 5.2.17 on 2026-09-14 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_alter_organization_video_provider"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        help_text="Whether the student is currently active in this academy.",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The academy the student is enrolled in.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_enrollments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The student user.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["organization_id", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "user"),
                        name="unique_student_enrollment",
                        violation_error_message="This student is already enrolled in this organization.",
                    )
                ],
            },
        ),
    ]
