# Generated by Django 5.2.17 on 2026-09-15 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0004_enforce_curriculum_tenancy"),
        ("organizations", "0004_studentenrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentenrollment",
            name="level",
            field=models.ForeignKey(
                blank=True,
                help_text="The student's current level in the track.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_enrollments",
                to="curriculum.level",
            ),
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="track",
            field=models.ForeignKey(
                blank=True,
                help_text="The academic track the student is enrolled in.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_enrollments",
                to="curriculum.track",
            ),
        ),
    ]
