# Generated by Django 5.2.17 on 2026-09-20 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_organizationinvitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Administrator"),
                    ("staff", "Staff"),
                    ("teacher", "Teacher"),
                    ("parent", "Parent"),
                    ("student", "Student"),
                ],
                help_text="The role the user will hold upon acceptance.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Administrator"),
                    ("staff", "Staff"),
                    ("teacher", "Teacher"),
                    ("parent", "Parent"),
                    ("student", "Student"),
                ],
                help_text="Authority inside this academy. Independent of User.role — a user may be 'teacher' here and 'student' globally.",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="InvitationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        default="email",
                        help_text="Channel used for delivery.",
                        max_length=32,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="Provider adapter identifier (e.g. 'email_smtp').",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Delivery status outcome.",
                        max_length=32,
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of delivery attempts executed."
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        help_text="Identifier returned by the external provider.",
                        max_length=255,
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        help_text="Machine-readable error code if failed.",
                        max_length=64,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Human-readable error details if failed."
                    ),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the latest delivery attempt.",
                        null=True,
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when delivery was confirmed.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invitation",
                    models.ForeignKey(
                        help_text="The invitation this delivery attempt was for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="organizations.organizationinvitation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
    ]
