# Generated by Django 5.2.17 on 2026-09-26 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_alter_organizationinvitation_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="studentenrollment",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="The teacher assigned to instruct this student in this academy.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_student_enrollments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
