# Generated by Django 5.2.17 on 2026-10-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_studentenrollment_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="paystack_subaccount_code",
            field=models.CharField(
                blank=True,
                help_text="Paystack subaccount code for routing tuition directly to the academy bank account.",
                max_length=100,
                null=True,
            ),
        ),
    ]
