# Generated by Django 5.2.17 on 2026-09-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="valid_rows",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
