# Generated by Django 5.2.17 on 2026-09-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0002_importjob_valid_rows"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="emails_failed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importjob",
            name="emails_sent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importjob",
            name="invitations_created",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
