# Generated by Django 5.2.17 on 2026-08-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="specialties",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tracks this teacher is eligible to teach. Recorded now, not enforced: Phase 4's routing is what matches a level's track against this (see tech-debt.md).",
                related_name="specialist_teachers",
                to="curriculum.track",
            ),
        ),
    ]
