# Generated by Django 5.2.17 on 2026-09-05 14:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_teacherprofile_specialties"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationTeacherConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_weekly_hours",
                    models.PositiveIntegerField(
                        help_text="Capacity dial for this academy only. Scheduling still enforces TeacherProfile.max_weekly_hours until scheduling tenancy lands.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "hourly_payout_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="What this academy pays per hour. Null means no per-hour rate, as on TeacherProfile. Payout calculation still reads that one.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False,
                        help_text="Approved to teach *here*. An academy approves its own teachers, so a teacher may be approved by one and not another.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "membership",
                    models.OneToOneField(
                        help_text="The academy-and-teacher relationship these terms apply to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_configuration",
                        to="organizations.organizationmembership",
                    ),
                ),
            ],
            options={
                "ordering": ["membership_id"],
            },
        ),
    ]
