# Generated by Django 5.2.17 on 2026-10-03 11:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_pendingparentlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationteacherconfiguration",
            name="compensation_type",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("per_class", "Per Class"),
                    ("fixed_period", "Fixed Period"),
                ],
                default="hourly",
                help_text="Compensation structure: hourly, per_class, or fixed_period.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organizationteacherconfiguration",
            name="fixed_period_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed compensation amount paid per cadence period.",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="organizationteacherconfiguration",
            name="fixed_period_cadence",
            field=models.CharField(
                blank=True,
                choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                help_text="Cadence for fixed period compensation: weekly or monthly.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organizationteacherconfiguration",
            name="per_class_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed payment per completed class/session.",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="organizationteacherconfiguration",
            name="hourly_payout_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="What this academy pays per hour. Null means no per-hour rate, as on TeacherProfile. Payout calculation reads this when compensation_type is hourly.",
                max_digits=8,
                null=True,
            ),
        ),
    ]
