# Generated by Django 5.2.17 on 2026-08-30 15:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scheduling", "0005_alter_teacherbookinglock_revision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minutes_paid",
                    models.PositiveIntegerField(
                        help_text="Session length used in the calculation, snapshotted from the booking. Stored rather than derived so the record explains its own amount without depending on a row that could later be corrected.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "rate_used",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The teacher's hourly rate at generation time, snapshotted the same way PricingAgreement.standard_rate is: changing the live rate must not reprice a payout that has already been made.",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="minutes_paid / 60 × rate_used, rounded once. See payout_amount().",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="NGN",
                        help_text="ISO code, snapshotted. NGN today; conversion is out of scope.",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("finalized", "Finalized"),
                        ],
                        default="generated",
                        help_text="generated → finalized. Finalized records are immutable.",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "finalized_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Stamped when the lead finalizes. Null while generated.",
                        null=True,
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        help_text="The completed session earning this payout. OneToOne is the one-payout-per-booking rule; for a cohort it is the earliest seat of the session, and the other seats earn nothing of their own.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout",
                        to="scheduling.booking",
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when the paid session is a group class, so the unique constraint below can enforce one payout per cohort session. Always equal to booking.cohort.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="scheduling.cohort",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="The teacher who taught the session. Always booking.teacher.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["booking__start_time_utc", "booking__pk"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("cohort__isnull", False)),
                        fields=("cohort",),
                        name="unique_payout_per_cohort_session",
                        violation_error_message="That group-class session has already been paid; a cohort earns one payout, not one per seat.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("finalized_at__isnull", True), ("status", "generated")
                            ),
                            models.Q(
                                ("finalized_at__isnull", False), ("status", "finalized")
                            ),
                            _connector="OR",
                        ),
                        name="payout_finalized_at_matches_status",
                        violation_error_message="finalized_at is set exactly when status is 'finalized'.",
                    ),
                ],
            },
        ),
    ]
