# Generated by Django 5.2.17 on 2026-10-03 11:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_studentenrollment_teacher"),
        ("payouts", "0002_remediate_legacy_payouts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherpayout",
            name="compensation_type",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("per_class", "Per Class"),
                    ("fixed_period", "Fixed Period"),
                ],
                default="hourly",
                help_text="How this payout was calculated: hourly or per_class.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TeacherFixedPeriodPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(
                        help_text="Start of the compensation period in UTC."
                    ),
                ),
                (
                    "period_end",
                    models.DateTimeField(
                        help_text="End of the compensation period in UTC."
                    ),
                ),
                (
                    "cadence",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        help_text="Cadence: weekly or monthly.",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fixed compensation amount for the period.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="NGN", help_text="ISO code, NGN.", max_length=3
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "Generated"),
                            ("finalized", "Finalized"),
                        ],
                        default="generated",
                        help_text="generated → finalized.",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The academy paying this fixed compensation.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_period_payouts",
                        to="organizations.organization",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        help_text="The teacher owed this fixed period compensation.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_period_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["period_start", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "organization",
                            "teacher",
                            "period_start",
                            "period_end",
                        ),
                        name="unique_fixed_payout_per_org_teacher_period",
                        violation_error_message="A fixed period payout already exists for this teacher and period.",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("finalized_at__isnull", True), ("status", "generated")
                            ),
                            models.Q(
                                ("finalized_at__isnull", False), ("status", "finalized")
                            ),
                            _connector="OR",
                        ),
                        name="fixed_payout_finalized_at_matches_status",
                        violation_error_message="finalized_at is set exactly when status is 'finalized'.",
                    ),
                ],
            },
        ),
    ]
