# Generated by Django 5.2.17 on 2026-08-23 04:32

import curriculum.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=80, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Sequence within the track, 1 = first. Appended, never inserted.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "min_age",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Informational only in this phase — not a hard gate. A 10-year-old and a 40-year-old can both sit at Beginner Arabic.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "group_eligible",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this level may run as a cohort. Cohorts arrive in Phase 4; the data is captured now so routing has something to read.",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="curriculum.track",
                    ),
                ),
            ],
            options={
                "ordering": ["track", "order"],
            },
        ),
        migrations.CreateModel(
            name="PlacementResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_sample",
                    models.FileField(
                        blank=True,
                        help_text="Recitation sample. Empty when the student skipped as beginner.",
                        null=True,
                        upload_to=curriculum.models.placement_audio_path,
                    ),
                ),
                (
                    "skipped_as_beginner",
                    models.BooleanField(
                        default=False,
                        help_text="Student declared themselves a complete beginner instead of recording. Mutually exclusive with audio_sample.",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="pending",
                        help_text="Recomputed from reviewed_at on every save(); never set by a client.",
                        max_length=16,
                    ),
                ),
                (
                    "recommended_level",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null until reviewed. Must belong to this placement's track.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="placements",
                        to="curriculum.level",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The lead teacher who reviewed. Stays null for a beginner skip — that placement is a system decision, not a teacher's.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="placement_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement_results",
                        to="curriculum.track",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "track"),
                        name="unique_placement_per_student_track",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("skipped_as_beginner", True),
                                models.Q(
                                    ("audio_sample__isnull", True),
                                    ("audio_sample", ""),
                                    _connector="OR",
                                ),
                            ),
                            models.Q(
                                ("skipped_as_beginner", False),
                                ("audio_sample__isnull", False),
                                models.Q(("audio_sample", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="placement_audio_xor_beginner_skip",
                        violation_error_message="Provide exactly one of audio_sample or skipped_as_beginner.",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="level",
            constraint=models.UniqueConstraint(
                fields=("track", "order"), name="unique_level_order_per_track"
            ),
        ),
    ]
