# Generated by Django 5.2.17 on 2026-09-28 18:42

import curriculum.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0004_enforce_curriculum_tenancy"),
        ("organizations", "0008_studentenrollment_teacher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Book / Document"),
                            ("book", "Digital Book / Reader"),
                            ("worksheet", "Worksheet / Exercise"),
                            ("image", "Image / Infographic"),
                            ("audio", "Audio Recording"),
                            ("link", "External Resource / Web Link"),
                            ("text", "Text / Surah Excerpt / Notes"),
                        ],
                        default="pdf",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded PDF, document, or image file.",
                        null=True,
                        upload_to=curriculum.models.material_file_path,
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="External URL or embed link if not an uploaded file.",
                        max_length=500,
                    ),
                ),
                (
                    "content_text",
                    models.TextField(
                        blank=True,
                        help_text="Structured Arabic / English text, ayah passages, or study notes.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this material is active and accessible in the classroom.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional level this material belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_materials",
                        to="curriculum.level",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The academy that owns this learning material.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_materials",
                        to="organizations.organization",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional track this material belongs to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_materials",
                        to="curriculum.track",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_learning_materials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
