# Generated by Django 5.2.17 on 2026-09-12 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("booking_confirmed", "Booking Confirmed"),
                            ("booking_cancelled", "Booking Cancelled"),
                            ("placement_reviewed", "Placement Reviewed"),
                            ("progress_ready", "Progress Ready"),
                            ("teacher_invitation", "Teacher Invitation"),
                        ],
                        db_index=True,
                        help_text="The event type triggering this notification.",
                        max_length=32,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short headline summary.", max_length=200
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Human-readable notification text."
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON-serializable domain payload stripped of secrets or provider details.",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Academy-scoped idempotency key preventing duplicate notifications.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when recipient marked this notification read.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The academy this notification belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="organizations.organization",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="The recipient of this notification.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("push", "Push"),
                            ("in_app", "In-App"),
                        ],
                        db_index=True,
                        help_text="Channel used for delivery.",
                        max_length=32,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="Provider adapter identifier (e.g., 'email_smtp', 'meta_whatsapp').",
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Delivery status outcome.",
                        max_length=32,
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of delivery attempts executed."
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        help_text="Identifier returned by the external provider.",
                        max_length=255,
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        help_text="Machine-readable error code if failed.",
                        max_length=64,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Human-readable error details if failed."
                    ),
                ),
                (
                    "attempted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the latest delivery attempt.",
                        null=True,
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when delivery was confirmed.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        help_text="The notification being delivered.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__isnull", False)),
                fields=("organization", "idempotency_key"),
                name="unique_notification_org_idempotency_key",
            ),
        ),
    ]
